In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Student.csv")

In [3]:
df.head()

   Gender Age_Group  Income
0  female     18-25   25000
1    male     18-25   30000
2    male     26-35   40000
3  female     26-35   42000
4    male     18-25   28000

In [10]:
grouped = df.groupby('Gender')['Income'].agg(['mean','median','std','min','max'])
print(grouped)

           mean   median           std    min    max
Gender
female  41200.0  42000.0   9833.615815  25000  50000
male    35400.0  30000.0  10620.734438  27000  52000

In [12]:
df.columns

Index(['Gender', 'Age_Group', 'Income'], dtype='str')

In [14]:
income_list= df.groupby('Gender')['Income'].apply(list)
print(income_list)

Gender
female    [25000, 42000, 50000, 41000, 48000]
male      [30000, 40000, 28000, 52000, 27000]
Name: Income, dtype: object

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [7]:
grouped=df.groupby('Species').mean()
print(grouped)

                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5          5.006         3.418          1.464
Iris-versicolor   75.5          5.936         2.770          4.260
Iris-virginica   125.5          6.588         2.974          5.552

                 PetalWidthCm
Species
Iris-setosa             0.244
Iris-versicolor         1.326
Iris-virginica          2.026

In [8]:
stds=df.groupby('Species').std()
print(stds)

                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa      14.57738       0.352490      0.381024       0.173511
Iris-versicolor  14.57738       0.516171      0.313798       0.469911
Iris-virginica   14.57738       0.635880      0.322497       0.551895

                 PetalWidthCm
Species
Iris-setosa          0.107210
Iris-versicolor      0.197753
Iris-virginica       0.274650

In [9]:
all=df.groupby('Species').describe(include='all')
print(all)

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [10]:
df.groupby('Species').quantile([0.25,0.50,0.75])

                          Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa     0.25   13.25          4.800         3.125          1.400
                0.50   25.50          5.000         3.400          1.500
                0.75   37.75          5.200         3.675          1.575
Iris-versicolor 0.25   63.25          5.600         2.525          4.000
                0.50   75.50          5.900         2.800          4.350
                0.75   87.75          6.300         3.000          4.600
Iris-virginica  0.25  113.25          6.225         2.800          5.100
                0.50  125.50          6.500         3.000          5.550
                0.75  137.75          6.900         3.175          5.875

                      PetalWidthCm
Species
Iris-setosa     0.25           0.2
                0.50           0.2
                0.75           0.3
Iris-versicolor 0.25           1.2
                0.50           1.3
                0.75           1.5
Iris-virginica  0.25           1.8
                0.50           2.0
                0.75           2.3